config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  resources :money_transactions
  resources :users
  get 'static/help'
  get 'static/privacy'
  root to: 'static#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/money_transaction.rb
# frozen_string_literal: true

class MoneyTransaction < ApplicationRecord
  belongs_to :creditor, class_name: 'User'
  belongs_to :debitor, class_name: 'User'

  validates :amount, presence: true, numericality: { greater_than: 0 }

  validate :check_creditor_and_debitor

  def check_creditor_and_debitor
    errors.add(:debitor_id, "can't be the same as creditor") if creditor_id == debitor_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :credits, class_name: "MoneyTransaction", foreign_key: "creditor_id"
  has_many :debts, class_name: "MoneyTransaction", foreign_key: "debitor_id"  
  has_secure_password

  validates :email, :name, presence: true
  validates :email, :name, uniqueness: true


  def to_s
    name 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # TODO: only verify csrf_token when authentication is done without cookies
  skip_before_action :verify_authenticity_token, if: :json_request?

  before_action :coerce_json

  def coerce_json
    if json_request?
      request.format = :json
    end
  end

  def json_request?
    request.headers[ 'HTTP_ACCEPT' ] =~ /^\s*application\/json/
  end
end

app/controllers/money_transactions_controller.rb
# frozen_string_literal: true

class MoneyTransactionsController < ApplicationController
  before_action :set_money_transaction, only: %i[show edit update destroy]

  # GET /money_transactions
  # GET /money_transactions.json
  def index
    @money_transactions = MoneyTransaction.all
  end

  # GET /money_transactions/1
  # GET /money_transactions/1.json
  def show; end

  # GET /money_transactions/new
  def new
    @money_transaction = MoneyTransaction.new
  end

  # GET /money_transactions/1/edit
  def edit; end

  # POST /money_transactions
  # POST /money_transactions.json
  def create
    @money_transaction = MoneyTransaction.new(money_transaction_params)

    respond_to do |format|
      if @money_transaction.save
        format.html { redirect_to money_transactions_path, notice: 'Money transaction was successfully created.' }
        format.json { render :show, status: :created, location: @money_transaction }
      else
        format.html { render :new }
        format.json { render json: @money_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /money_transactions/1
  # PATCH/PUT /money_transactions/1.json
  def update
    respond_to do |format|
      Rails.logger.warn(money_transaction_params)
      if @money_transaction.update(money_transaction_params)
        format.html { redirect_to money_transactions_path, notice: 'Money transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @money_transaction }
      else
        Rails.logger.warn(@money_transaction.errors.to_json)

        format.html { render :edit }
        format.json { render json: @money_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /money_transactions/1
  # DELETE /money_transactions/1.json
  def destroy
    @money_transaction.destroy
    respond_to do |format|
      format.html { redirect_to money_transactions_url, notice: 'Money transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_money_transaction
    @money_transaction = MoneyTransaction.find(params[:id])
  end

  def money_transaction_params
    params.require(:money_transaction).permit(:creditor_id, :debitor_id, :amount, :paid_at)
  end
end

app/controllers/static_controller.rb
# frozen_string_literal: true

class StaticController < ApplicationController
  def home; end

  def help; end

  def privacy; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(register_user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    begin
      @user.destroy
    rescue ActiveRecord::RecordNotFound
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User not found.' }
        format.json { render json: { "error": 'User not found' }, status: :not_found }
      end
      return
    rescue ActiveRecord::InvalidForeignKey
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User cannot be deleted.' }
        format.json { render json: { "error": 'User cannot be deleted' }, status: :forbidden }
      end
      return
    rescue StandardError
      raise
    rescue Exception
      raise
    end

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :name)
  end

  def register_user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def mdl_select(model_and_name, options, value)
        model, name = model_and_name.split('[')
        name.chop!
        label = model.camelize.constantize.human_attribute_name(name)
        name = model_and_name
        if value
            visible_value = options.select{|i| i[1] == value}.first[0]
        else
            visible_value = ''
        end
        render "mdl_select", { name: name, model_and_name: model_and_name, model: model, label: label, options: options, visible_value: visible_value, value: value }
    end
end

app/helpers/money_transactions_helper.rb
module MoneyTransactionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IOU - i owe you</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'iou' %>
    <%= javascript_pack_tag 'iou', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.teal-orange.min.css" />     
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body style="background-color: red;">
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer
                mdl-layout--fixed-header">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <div class="mdl-layout-spacer"></div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable
                      mdl-textfield--floating-label mdl-textfield--align-right">
            <label class="mdl-button mdl-js-button mdl-button--icon"
                  for="fixed-header-drawer-exp">
              <i class="material-icons">search</i>
            </label>
            <div class="mdl-textfield__expandable-holder">
              <input class="mdl-textfield__input" type="text" name="sample"
                    id="fixed-header-drawer-exp">
            </div>
          </div>
        </div>
      </header>
      <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">IOU - i owe you</span>
        <nav class="mdl-navigation">
            <%= link_to "Home", root_path, class: 'mdl-navigation__link' %>
            <%= link_to "Users", users_path, class: 'mdl-navigation__link' %>
            <%= link_to "Transactions", money_transactions_path, class: 'mdl-navigation__link' %>
            <%= link_to "API Doc", rswag_ui_path, class: 'mdl-navigation__link' %>
        </nav>
      </div>
      <main class="mdl-layout__content constrain">
      <p id="notice"><%= notice %></p>  
      <%= yield %>
      </main>
      <footer class="mdl-mini-footer">
        <div class="mdl-mini-footer__left-section">
          <div class="mdl-logo">IOU - i owe you</div>
          <ul class="mdl-mini-footer__link-list">
            <li><%= link_to "Help", static_help_path %></li>
            <li><%= link_to "Privacy & Terms", static_privacy_path %></li>
          </ul>
        </div>
      </footer>      
    </div>
  </body>
</html>



        

app/views/money_transactions/_mdl_select.html.erb
<div class="mdl-textfield mdl-js-textfield getmdl-select">
    <input type="text" value="<%= visible_value %>" class="mdl-textfield__input" id="<%= model_and_name %>" readonly>
    <input type="hidden" value="<%= value %>" name="<%= model_and_name %>">
    <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
    <label for="<%= model_and_name %>" class="mdl-textfield__label"><%= label %></label>
    <ul for="<%= model_and_name %>" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
      <% options.each do |name, id| %>
        <li class="mdl-menu__item" data-val="<%= id %>"><%= name %></li>
      <% end %>
    </ul>
</div>

app/views/money_transactions/edit.html.erb
<h1>Settle this Dept</h1>

<p>
  <%= @money_transaction.creditor %> 
  lent <%= number_to_currency(@money_transaction.amount, unit: '€') %>
  to <%= @money_transaction.debitor %>
</p>

<p>Was this debt settled?  If yes, enter the date it was settled on. Leave the date empty if it 
was not settled yet.</p>

<%= mdl_form_for(@money_transaction) do |form| %>
  <% if @money_transaction.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@money_transaction.errors.count, "error") %> prohibited this money_transaction from being saved:</p>

      <ul>
        <% @money_transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <%= form.date_field :paid_at, value: Date.today %>
  <br>

  <%= form.submit  class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent", value: "Save"  %>

<% end %>

app/views/money_transactions/index.html.erb
<h1>Money Transactions</h1>

<table  class="mdl-data-table mdl-js-data-table">
  <thead>
    <tr>
      <th>Creditor</th>
      <th></th>      
      <th>Debitor</th>
      <th>Amount</th>
      <th>Paid at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @money_transactions.each do |money_transaction| %>
      <tr>
        <td><%= money_transaction.creditor %></td>
        <td> <i class="material-icons">arrow_right_alt</i> </td>
        <td><%= money_transaction.debitor %></td>
        <td><%= number_to_currency(money_transaction.amount, unit: '€') %></td>
        <td><%= money_transaction.paid_at %></td>
        <td><%= link_to 'Show', money_transaction %></td>
        <td><%= link_to 'Edit', edit_money_transaction_path(money_transaction) %></td>
        <td><%= button_to 'Destroy', money_transaction, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Money Transaction', new_money_transaction_path %>

app/views/money_transactions/new.html.erb
<h1>New Money Transaction</h1>

<%= mdl_form_for(@money_transaction) do |form| %>
  <% if @money_transaction.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@money_transaction.errors.count, "error") %> prohibited this money_transaction from being saved:</p>

      <ul>
        <% @money_transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= mdl_select('money_transaction[creditor_id]', User.all.collect {|u| [u.name, u.id]}, @money_transaction&.creditor_id) %>

  <br>

  <%= mdl_select('money_transaction[debitor_id]', User.all.collect {|u| [u.name, u.id]}, @money_transaction&.debitor_id) %>

  <br>

  <%= form.text_field :amount %>
  <br>



  <%= form.submit  class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent", value: "Save"  %>

<% end %>

app/views/money_transactions/show.html.erb
<p>
  <strong>Creditor:</strong>
  <%= @money_transaction.creditor %>
</p>

<p>
  <strong>Debitor:</strong>
  <%= @money_transaction.debitor %>
</p>

<p>
  <strong>Amount:</strong>
  <%= number_to_currency(@money_transaction.amount, unit: '€') %>
</p>

<p>
  <% if @money_transaction.paid_at.nil? %>
    <strong>Not paid yet</strong>
  <% else %>
  <strong>Paid at:</strong>
  <%=l @money_transaction.paid_at %>
  <% end %>
</p>

<%= link_to 'Edit', edit_money_transaction_path(@money_transaction) %> |
<%= link_to 'Back', money_transactions_path %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= mdl_form_for(@user) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</p>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <%= form.text_field :email %> <br>

  <%= form.submit class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" %>

<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="mdl-data-table mdl-js-data-table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= button_to 'Destroy', user, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Register User</h1>

<%= mdl_form_for(@user) do|form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</p>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :name %> <br>

  <%= form.text_field :email %> <br>

  <%= form.password_field :password %> <br>


  <%= form.password_field :password_confirmation %> <br>


  <%= form.submit class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent", value: "Register User" %>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>


<p>
  <strong>ID:</strong>
  <%= @user.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>


<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>